version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: 'prueba-tyba'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - 5432:5432
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - redis
      - postgres
    ports:
      - 8000:8000